### ISSUE TITLE
Hello Trojan Not working

### ISSUE THREAD

**Issue by muzaffer72** [missuo/XrayR-V2Board#15]
I have problem. v2ray and shadowsocks run. But trojan not working or ı dont know settings

**Comment by missuo** [comment]
Hello.
Since I don't use Trojan myself, but the reason Trojan has problems is not that there is a problem with my script. Rather, Trojan requires a configured SSL certificate to work properly, just like TLS in V2Ray, and you can't use it. Please configure your own certificate. Please explore the specific method yourself, thanks.
